Undo redo
disc-in/UltimateApp pull request #282
Opened 2021-01-05 10:41 UTC by ZacharieALES

Add undo and redo buttons to the editor.

2021-01-05 11:37 UTC, guillaumemoby commented
Proposition de design
Le toggle button n'est pas encore d'actualité mais voici le design que j'ai en tête
![designforZach-01](https://user-images.githubusercontent.com/56125567/103641848-a8a17c00-4f52-11eb-9ef7-9f50f4ca6590.png)

2021-01-05 22:49 UTC, guillaumemoby submitted a review, later dismissed

2021-01-06 03:37 UTC, sallesma requested changes
Il y a encore quelques bugs :
- le compteur des DraggableElements est faut quand on ajoute plusieurs joueurs puis fait undo, puis rajoute, puis fait undo, etc.
- il faut que je teste sur ios
- il faut ajouter des tests

2021-01-07 13:21 UTC, guillaumemoby commented
Proposition de design:
![designeditor-01](https://user-images.githubusercontent.com/56125567/103897310-9d398680-50f3-11eb-8516-3209edc85080.png)

2021-01-11 15:50 UTC, sallesma approved these changes

2021-01-11 15:50 UTC, merged